spring.application.name=hexagonal

### MICROSERVICES ADDRESS ###
hexagonal.client.address.response.url=https://b4db50f5-217c-47d9-a3ad-c9f93e89ff5d.mock.pstmn.io/addresses
hexagonal.message.producer.topic.cpf.validation=topic-cpf-validation
hexagonal.message.producer.topic.cpf.validated=topic-cpf-validated

### MONGODB ###
spring.data.mongodb.port=27017
spring.data.mongodb.username=root
spring.data.mongodb.host=localhost
spring.data.mongodb.password=example
spring.data.mongodb.database=hexagonal
spring.data.mongodb.authentication-database=admin


### KAFKA ###
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=hexagonal-consumer

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{correlationID}] %msg%n
