spring.application.name=hexagonal

### MICROSERVICES ADDRESS ###
hexagonal.client.addressResponse.url=http://localhost:8081

### MONGODB ###
spring.data.mongodb.uri=mongodb://localhost:27017/udemy-cursos.hexagonal


### KAFKA ###
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=hexagonal-consumer
