spring.application.name=hexagonal

### MICROSERVICES ADDRESS ###
hexagonal.client.address.url=http://localhost:8081

### MONGODB ###
spring.data.mongodb.uri=mongodb://localhost:27017/udemy-cursos.hexagonal
